// Regenerates public/sw.js with the current package.json version baked
// into CACHE_NAME. Runs automatically before `next build` / `next dev`
// (see the "prebuild"/"predev" npm scripts) so every release
// automatically gets a fresh, empty cache — which is what makes the
// in-app "check for updates" button deterministic: after an update, the
// very first request is guaranteed to hit the network, not stale cache.
//
// Served as a plain static file from public/ (not a route handler) —
// tested and confirmed that's the reliable way to serve a service
// worker script here; a dynamically-generated route handler response
// failed registration with "an unknown error occurred when fetching
// the script" in this project's dev/preview environment.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf-8")
);
const CACHE_NAME = `salsa-berlin-2026-v${pkg.version}`;

const APP_SHELL = [
  "/",
  "/itinerary",
  "/flights",
  "/hotel",
  "/congress",
  "/moto",
  "/documents",
  "/expenses",
  "/todo",
  "/packing",
  "/music",
  "/transport",
  "/food",
  "/manifest.webmanifest",
];

const script = `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit by hand.
// Regenerated automatically on every build/dev start from package.json's
// version (currently ${pkg.version}). Edit scripts/generate-sw.mjs instead.

const CACHE_NAME = ${JSON.stringify(CACHE_NAME)};
const APP_SHELL = ${JSON.stringify(APP_SHELL, null, 2)};

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      Promise.allSettled(
        APP_SHELL.map((url) => cache.add(url).catch(() => {}))
      )
    )
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name !== CACHE_NAME)
            .map((name) => caches.delete(name))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // let cross-origin (e.g. currency API) hit the network directly

  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      const cached = await cache.match(request);
      const networkFetch = fetch(request)
        .then((response) => {
          if (response && response.status === 200) {
            cache.put(request, response.clone());
          }
          return response;
        })
        .catch(() => cached);

      return cached || networkFetch;
    })
  );
});
`;

const outPath = path.join(__dirname, "..", "public", "sw.js");
fs.writeFileSync(outPath, script, "utf-8");
console.log(`[generate-sw] wrote ${outPath} (CACHE_NAME=${CACHE_NAME})`);
